MakhazenMVC/Models/ErrorViewModel.cs
namespace MakhazenMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MakhazenMVC/Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;

namespace MakhazenMVC.PL.Controllers
{
	public class BookingController : Controller
	{
		public IActionResult Booking()
		{
			return View();
		}
	}
}

MakhazenMVC/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;

namespace MakhazenMVC.PL.Controllers
{
	public class FeedbackController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

MakhazenMVC/Controllers/HomeController.cs
using MakhazenMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MakhazenMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MakhazenMVC/Controllers/ProviderController.cs
using Microsoft.AspNetCore.Mvc;

namespace MakhazenMVC.PL.Controllers
{
	public class ProviderController : Controller
	{
		public IActionResult Provider()
		{
			return View();
		}
	}
}

MakhazenMVC/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;

namespace MakhazenMVC.PL.Controllers
{
	public class ReportController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

MakhazenMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace MakhazenMVC.PL.Controllers
{
	public class UserController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

MakhazenMVC/Views/Booking/Booking.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

    

    <div class="booking-form">
        <label for="">Full Name</label>
        <input type="text" class="form-control" placeholder="Enter your Full Name">
        <label for="">Phone Number</label>
        <input type="text" class="form-control" placeholder="Enter your Phone Number">
        <!-- <div class="input"> -->
        <div class="options">
            <label> Select Size</label>
            <select class="size">
                <option value="">Choose one</option>
                <option value="">400cm*250cm(All)</option>
                <option value="">50cm*50cm</option>
                <option value="">100cm*150cm</option>
                <option value="">200cm*100cm</option>
            </select>
        </div>
        <!-- <select class="customer-select">
            <option value="1">400cm*250cm(All)</option>
            <option value="2">50cm*50cm</option>
            <option value="3">100cm*150cm</option>
            <option value="4">200cm*100cm</option> -->
        <div class="input">
            <label>From</label>
            <input type="date" class="form-control select-date">
        </div>

        <div class="input">
            <label>To</label>
            <input type="date" class="form-control select-date">

        </div>

        <div class="inputt">
            <button onclick="window.location.href='payment.html'" type="button" class="btn btn-primary store">Pay</button>
        </div>
    </div>

MakhazenMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>


<p>
    Connect with ease! Our platform links available rooms to entrepreneurs
    seeking store space. List your room or find your perfect store location effortlessly.
    Unlock shared opportunities for property owners and business dreamers. Join us today!
</p>

MakhazenMVC/Views/Home/Index.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">


        <div class="carousel-inner" style="height: 300px;">
            @* حجم موحد للصور في السلايد الهيدر  *@

            <div class="carousel-item active">
                <img class="d-block w-100" src="./Images/about1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="./Images/about2.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="./Images/about3.jpg" alt="Third slide">

            </div>
        </div>
    </div>

    <div class="carousel-caption d-none d-md-block text-white">
        <h3 style="letter-spacing: 2px; line-height: 1.5; margin-bottom: 70px; font-weight:400;">KEEP YOUR ITEMS <br /> SAVE WITH US</h3>
    </div>
    @* الاسهم الي تغير الصور  *@
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>



<div class="Aboutus " style="margin-top:7%" id="About-sec">



    <h2 id="Aboutas">About Us:</h2>
    </br>

    <p class="About1">
        Connect with ease!</br>
        We are here to serve you find your best space for you to store your items safely
        Our platform links available rooms to entrepreneurs
        seeking store space.</br>Welcome to our dedicated platform where we strive to serve you in finding the ideal space to securely store your items. Whether you're a property owner looking to make the most of your available
        space or an entrepreneur seeking the perfect storage solution, we've got you covered.

        Our user-friendly platform seamlessly connects
        available rooms with individuals and businesses
        in search of storage space. List your room effortlessly
        or browse through our extensive listings to find the
        perfect store location tailored to your needs.

        By joining our community, you unlock shared opportunities for
        property owners and aspiring business leaders alike.
        It's not just about finding a space; it's about fostering connections and creating mutually
        beneficial partnerships.

        Take the first step towards realizing your storage goals and business dreams. Join us today!
    </p>
</div>

<div class="inquiries">
    <form class="form-inline">
        <div class="form-group mb-2">
            <h4>Enter your email for special offers</h4>
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <label for="inputEmail" class="sr-only">Email</label>
            <input type="email" class="form-control" style="width:auto;" id="input" placeholder="Makhazen@Makhazen.com">
            <button type="submit" class="btn btn-primary mb-2">Send</button>
        </div>
    </form>
</div>




<div class="ag-format-container">
    <div class="ag-courses_box">
        <div class="ag-courses_item">
            <a href="#" class="ag-courses-item_link">
                <div class="ag-courses-item_bg"></div>

                <div class="ag-courses-item_title">
                    Provide a place to Display your space as a store for rent.
                </div>


            </a>
        </div>

        <div class="ag-courses_item">
            <a href="#" class="ag-courses-item_link">
                <div class="ag-courses-item_bg"></div>

                <div class="ag-courses-item_title">
                    Provide Best stores in Oman for our clients.
                </div>


            </a>
        </div>

        <div class="ag-courses_item">
            <a href="#" class="ag-courses-item_link">
                <div class="ag-courses-item_bg"></div>

                <div class="ag-courses-item_title">
                    The best Prices for stores
                </div>


            </a>
        </div>





    </div>
</div>

<!-- Add Bootstrap JavaScript and jQuery scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</div>

MakhazenMVC/Views/Home/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>LogIn Page</h1>

MakhazenMVC/Views/Provider/Provider.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MakhazenMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MakhazenMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MakhazenMVC.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3 " style="background-color: whitesmoke">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MakhazenHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="#About-sec">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Provider" asp-action="Index" >Provider</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Booking">Booking</a>
                        </li>
                        <li class="nav-item ms-auto">
                            <button style="border-radius: 7px; width:100px;" class="btn btn-outline-primary text-dark my-2 my-sm-0" value="submit" asp-area="" asp-controller="Home" asp-action="Login">Login</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
          
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MakhazenMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>